### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by mikecx** [dennisduong/react-tipsy#1]
Hey,

Love the library! It's the first out of 8-10 that I tried that positioned properly, rendered properly, and didn't cause odd performance issues.

In your docs you have it marked as position: ["top", "bottom", "left", "right"] but in practice/the code it's actually placement: ["top", "bottom", "left", "right"]. 

Cheers and thanks for the great library!

**Comment by dennisduong** [comment]
mikecx,

Hey thanks for the heads up! I'll correct it and push the changes soon!
