### ISSUE TITLE
ReactDOM peer dependency warning even though it is installed

### ISSUE THREAD

**Issue by graulund** [dennisduong/react-tipsy#8]
Hi! Thanks for a great product! I'm getting the following warning, even though I have `react-dom@15.5.4` installed:

```
npm WARN react-tipsy@0.5.0 requires a peer of react-dom@15.5.0 but none was installed.
```

Could it be that the version range needs to be specified as `^15.5.0` and not `15.5.0` [in the `package.json` file](https://github.com/dennisduong/react-tipsy/blob/master/package.json#L43)? Just like it has been done for the `react` peer dependency?

Thanks!

**Comment by dennisduong** [comment]
Yes I believe that is correct. Could you submit a merge request? I'll go ahead and merge + close this issue out.

**Comment by graulund** [comment]
Yep, here you go! https://github.com/dennisduong/react-tipsy/pull/9

**Comment by graulund** [comment]
Hey @dennisduong, can I get you to publish a new version on npm? Otherwise the fix doesn't have any real effect. Thanks! 👍

**Comment by dennisduong** [comment]
Sorry for the late response. I went ahead and published a new version on NPM just now.
